<a href="https://colab.research.google.com/github/sukritganesh/Algorithms/blob/master/Sorting_Algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preamble

This notebook contains a collection of popular sorting algorithms. Feel free to use them, modify them, and play around with them to heart's content. These sorting algorithms are great for educational or practical applications!

In [7]:
import numpy as np
import math
import random
import copy

# Selection Sort

Selection sort involves finding the minimum element in the array and moving it to the front.

Time Complexity: O(n^2)

In [5]:
def selectionSort(arr):
  for i in range(len(arr)):
    # step 1: find the minimum element in the current subarray
    minVal = arr[i]
    minIdx = i
    for j in range(i, len(arr), 1):
      if (arr[j] < minVal):
        minVal = arr[j]
        minIdx = j
      
    # step 2: swap the minimum value with the first value in the current subarray
    temp = arr[minIdx]
    arr[minIdx] = arr[i]
    arr[i] = temp

    # now, repeat the process, but with the last i-1 elements
    # we shrink the size of our unsorted subarray, as we have placed another element in the right position

  return arr 

In [10]:
# Selection Sort Examples
print('\nSelection Sort Examples:\n')

arr1 = np.random.randint(low = -10, high = 10, size = 8)
arr2 = [1]
arr3 = [1, 4, 6, 4, 1]
arr4 = [0, -1323, 0.222, 0.377232, 411.823]

arrs = [arr1, arr2, arr3, arr4]

for arr in arrs:
  print(arr, end=' ')
  selectionSort(arr)
  print('sorted:', arr)



Selection Sort Examples:

[ -3   9   7 -10   7   7   1  -8] sorted: [-10  -8  -3   1   7   7   7   9]
[1] sorted: [1]
[1, 4, 6, 4, 1] sorted: [1, 1, 4, 4, 6]
[0, -1323, 0.222, 0.377232, 411.823] sorted: [-1323, 0, 0.222, 0.377232, 411.823]


# Insertion Sort

Best Case: O(n)

Worst Case: O(n^2)

Average: O(n^2)



In [12]:
def insertionSort(arr):
  for i in range(1, len(arr), 1):
    currKey = arr[i]
    j = i - 1

    while (j >= 0 and arr[j] > currKey): 
      # move up if arr[j] > currKey
      if (arr[j] > currKey):
        arr[j + 1] = arr[j]
      j -= 1
    
    # once you've reached the correct position, insert currKey
    arr[j + 1] = currKey
      
  return arr


In [13]:
# Insertion Sort Examples
print('\nInsertion Sort Examples:\n')

arr1 = np.random.randint(low = -10, high = 10, size = 8)
arr2 = [1]
arr3 = [1, 4, 6, 4, 1]
arr4 = [0, -1323, 0.222, 0.377232, 411.823]

arrs = [arr1, arr2, arr3, arr4]

for arr in arrs:
  print(arr, end=' ')
  insertionSort(arr)
  print('sorted:', arr)



Insertion Sort Examples:

[-2 -7 -1  6  2  7  7  2] sorted: [-7 -2 -1  2  2  6  7  7]
[1] sorted: [1]
[1, 4, 6, 4, 1] sorted: [1, 1, 4, 4, 6]
[0, -1323, 0.222, 0.377232, 411.823] sorted: [-1323, 0, 0.222, 0.377232, 411.823]


# Bubble Sort

Bubble sort works by "bubbling" the highest values to the highest index in the array. Algorithm terminates immediately after array is sorted.

Best Case: O(n)

Worst Case: O(n^2)

Average: O(n^2)

In [14]:
def bubbleSort(arr):
  for i in range(len(arr) - 1, 1, -1):
    currSwaps = 0   # keeps track of number of swaps this iteration
    for j in range(i - 1):
      if (arr[j] > arr[j + 1]):
        # swap arr[j] and arr[j + 1]
        temp = arr[j]
        arr[j] = arr[j + 1]
        arr[j + 1] = temp
        currSwaps += 1

    # if no swaps are made, array is sorted
    if (currSwaps == 0):
      return arr

  return arr

In [18]:
# Bubble Sort Examples
print('\nBubble Sort Examples:\n')

arr1 = np.random.randint(low = -10, high = 10, size = 8)
arr2 = [1]
arr3 = [1, 4, 6, 4, 1]
arr4 = [0, -1323, 0.222, 0.377232, 411.823]
arr5 = [0, 1, 2, 3, 5, 4, 6, 7, 8, 9]

arrs = [arr1, arr2, arr3, arr4, arr5]

for arr in arrs:
  print(arr, end=' ')
  bubbleSort(arr)
  print('sorted:', arr)



Bubble Sort Examples:

[  8  -6  -9  -5  -1  -8 -10   4] sorted: [-10  -9  -8  -6  -5  -1   8   4]
[1] sorted: [1]
[1, 4, 6, 4, 1] sorted: [1, 4, 4, 6, 1]
[0, -1323, 0.222, 0.377232, 411.823] sorted: [-1323, 0, 0.222, 0.377232, 411.823]
[0, 1, 2, 3, 5, 4, 6, 7, 8, 9] sorted: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
